         


  modal: {            tooltip: {
                bold: "粗体",
                italic: "斜体",
                strikethrough: "删除线",
                quote: "引用",
                picture: "插入图片",
                h1: "标题1",
                h2: "标题2",
                h3: "标题3",
                h4: "标题4",
                hr: "分割线",
                link: "插入链接",
                video: "插入视频",
                audio: "插入音频",
                audioExist: "已有音频",
                "math-formula": "数学公式",
                undo: "撤销",
                redo: "重做",
                history: "历史版本",
                save: "保存",
                expand: "全屏",
                compress: "退出全屏",
                preview: "切换到预览模式",
                "to-normal-mode": "返回",
                grammar: "Markdown语法参考"
            },
            pubbtn: {
                publishing: "发布中...",
                saving: "保存中...",
                saved: "已保存",
                "save-fail": "保存失败,请手动保存",
                publicize: "发布文章",
                publicized: "已发布",
                "cancel-publish": "取消发布",
                "publish-update": "发布更新",
                "compile-paid-note": "发布更新和设置",
                "publicize-paid-note": "发布为付费文章",
                "audio-transcoding": "音频转码中，请稍后发布"
            },
            modal: {
                insertimg: "插入图片",
                insertlink: "插入链接",
                insertvideo: "插入视频",
                removeLink: "删除链接",
                confirm: "确认",
                cancel: "取消",
                urldes: "链接地址",
                "getting-linkinfo": "正在获取链接标题...",
                "getting-linkinfo-fail": "无法获取链接标题,请手动输入链接文本",
                linktxtdes: "链接文本",
                insertimgdes: "点击上传（可多张）",
                imgpolicy: "图片私密性",
                chooseurlimg: "或选择网络图片",
                imglinkdes: "请输入网络图片链接",
                choosesysimg: "或上传本地图片",
                "only-support": "目前只支持",
                tc: "腾讯",
                yk: "优酷",
                video: "视频",
                "video-url-des": "请输入视频地址",
                "wrong-video-source": "暂不支持此视频地址",
                "video-loading": "正在加载视频，请稍等...",
                "fetch-video-info-failed": "抱歉，您输入的地址无法识别！",
                "insert-audio": "插入音频",
                "upload-audio": "点击上传",
                "audio-support": "支持 {format} 格式，大小不超过 {size} M",
                "audio-cancle": "取消上传",
                "audio-upload-unfinished": "音频上传尚未完成",
                "reupload-audio": "重新上传",
                retry: "重试",
                "audio-upload-failed": "上传失败",
                "audio-uploading-failed": "音频未上传成功",
                "audio-upload-complete": "上传完成",
                "audio-upload-error": "网络异常，请稍后再试",
                "audio-name": "音频名称",
                "audio-author": "音频作者",
                "insert-audio-name": "输入音频名称",
                "insert-audio-author": "输入音频的创作者",
                "delete-audio": "删除音频",
                "audio-confirm": " 确定",
                "audio-overlarge": "文件大小超过限制！",
                "audio-delete": "确认删除音频吗？",
                "no-name": "佚名",
                "close-audio-warning": "确认关闭吗？",
                "close-audio-warning2": "关闭后，当前的更改或上传将丢失",
                "audio-transcoding": "音频正在转码，请稍候",
                "audio-edit": "编辑",
                "insert-math-formula": "插入数学公式",
                "common-expression": "常用表达式",
                "common-function": "常用函数",
                "common-symbol": "常用符号",
                "greek-alphabet": "希腊字母",
                "special-symbol": "特殊符号",
                "math-formula-grammar": "数学公式语法",
                "insert-empty": "输入内容为空，请重新输入！",
                "insert-audio-modal": "插入音频",
                "insert-audio-explain": "插入音频功能，仅对简书钻大于 {minJSD} 或被邀请的用户开放，你可以通过购买简书会员，或者积极参与简书社区互动（喜欢优质文章/喜欢自己的文章）等方式，增加你的简书钻"
            },
                insertimg: "插入图片",
                insertlink: "插入链接",
                insertvideo: "插入视频",
                removeLink: "删除链接",
                confirm: "确认",
                cancel: "取消",
                urldes: "链接地址",
                "getting-linkinfo": "正在获取链接标题...",
                "getting-linkinfo-fail": "无法获取链接标题,请手动输入链接文本",
                linktxtdes: "链接文本",
                insertimgdes: "点击上传（可多张）",
                imgpolicy: "图片私密性",
                chooseurlimg: "或选择网络图片",
                imglinkdes: "请输入网络图片链接",
                choosesysimg: "或上传本地图片",
                "only-support": "目前只支持",
                tc: "腾讯",
                yk: "优酷",
                video: "视频",
                "video-url-des": "请输入视频地址",
                "wrong-video-source": "暂不支持此视频地址",
                "video-loading": "正在加载视频，请稍等...",
                "fetch-video-info-failed": "抱歉，您输入的地址无法识别！",
                "insert-audio": "插入音频",
                "upload-audio": "点击上传",
                "audio-support": "支持 {format} 格式，大小不超过 {size} M",
                "audio-cancle": "取消上传",
                "audio-upload-unfinished": "音频上传尚未完成",
                "reupload-audio": "重新上传",
                retry: "重试",
                "audio-upload-failed": "上传失败",
                "audio-uploading-failed": "音频未上传成功",
                "audio-upload-complete": "上传完成",
                "audio-upload-error": "网络异常，请稍后再试",
                "audio-name": "音频名称",
                "audio-author": "音频作者",
                "insert-audio-name": "输入音频名称",
                "insert-audio-author": "输入音频的创作者",
                "delete-audio": "删除音频",
                "audio-confirm": " 确定",
                "audio-overlarge": "文件大小超过限制！",
                "audio-delete": "确认删除音频吗？",
                "no-name": "佚名",
                "close-audio-warning": "确认关闭吗？",
                "close-audio-warning2": "关闭后，当前的更改或上传将丢失",
                "audio-transcoding": "音频正在转码，请稍候",
                "audio-edit": "编辑",
                "insert-math-formula": "插入数学公式",
                "common-expression": "常用表达式",
                "common-function": "常用函数",
                "common-symbol": "常用符号",
                "greek-alphabet": "希腊字母",
                "special-symbol": "特殊符号",
                "math-formula-grammar": "数学公式语法",
                "insert-empty": "输入内容为空，请重新输入！",
                "insert-audio-modal": "插入音频",
                "insert-audio-explain": "插入音频功能，仅对简书钻大于 {minJSD} 或被邀请的用户开放，你可以通过购买简书会员，或者积极参与简书社区互动（喜欢优质文章/喜欢自己的文章）等方式，增加你的简书钻"
            },

 history: {
                "auto-save": "自动保存",
                publicize: "公开发表文章",
                update: "发布更新",
                recovery: "版本恢复",
                web: "简书网站",
                ios: "简书 iPhone App",
                android: "简书 Android App",
                "ios-night": "简书 iPhone App 黑夜版",
                timeago: "刚刚_秒以前_分钟以前_小时以前_天以前_周以前_月以前_年以前",
                "total-items": "共{num}条历史版本",
                filter: "筛选",
                "recovery-to": "恢复到这个版本"
            },
            trash: {
                trash: "回收站({num})",
                recovery: "恢复文章",
                recovering: "恢复文章中...",
                delete: "彻底删除",
                deleting: "彻底删除中...",
                "del-time": "将于{time}清除",
                "del-time2": "{time}天后清除"
            },

 verifymodal: {
                "sending-captcha": "{num}秒后重新发送",
                "resend-captcha": "重新发送验证码",
                "send-captcha": "发送验证码",
                "empty-captcha": "验证码为空",
                "verify-captcha-error": "验证码错误，请重试",
                "send-captcha-error": "验证码发送失败，可刷新页面重试",
                loading: "正在加载验证信息...",
                confirm: "确认",
                confirming: "确认中...",
                captcha: "验证码",
                title: "安全验证",
                "email-prefix": "用邮箱",
                "sms-prefix": "用手机",
                verify: "验证",
                "by-email": "用邮箱验证",
                "by-phone": "用手机短信验证",
                des: "为了保证你的账号安全，请先验证身份，验证成功后进行下一步操作，验证码{minute}分钟内有效"
            },
            app: {
                name: "简 书"
            },

 phoneModal: {
                all: "全部",
                clickbind: "点击绑定",
                bindtitle: "绑定手机号和微信",
                wxoccupy: "微信被占用",
                bindwx: "綁定微信",
                bindwxtip: "请使用微信扫描二维码进行绑定",
                nobind: "未绑定",
                bindwxphone: "绑定手机号和微信",
                yjjb: "一键绑定",
                cancel: "取消",
                bindtip: "发布公开文章需要同时绑定手机号和微信",
                tip: "绑定遇到问题",
                href: "点击查看帮助",
                "hot-countries": "热门国家和地区",
                "captcha-regex-error": "验证码格式不对，请重新输入",
                captcha: "短信验证码",
                title: "绑定手机",
                "phone-num": "手机号",
                "phone-error": "输入的手机号码有误，请重新输入",
                "get-otp-info-error": "获取国家区号失败, 请刷新页面重试"
            },

publishSuccessModal: {
                "post-des": "向专题投稿，让文章被更多人发现",
                "success-des": "发布成功，点击查看文章",
                "search-collection": "搜索专题",
                "new-collection": "新建",
                "my-collections": "我管理的专题",
                "lastest-collections": "最近投稿",
                "recomend-collections": "推荐专题",
                "include-note": "收录",
                "including-note": "收录中",
                "included-note": "已收录",
                "post-note": "投稿",
                "posting-note": "投稿中",
                "posted-note": "等待审核",
                "copy-success": "已复制到剪贴板中",
                "get-more-data": "点击加载更多",
                "no-more-data": "没有更多了",
                "copy-fail": "此浏览器不支持，复制失败，建议用Chrome"
            },
            collections: {
                "note-num": "{num}篇文章",
                "suber-num": "{num}人关注"
            },
            "upload-img": {
                "upload-success": "上传成功",
                "upload-fail": "上传失败",
                "upload-size-error": "上传图片尺寸错误",
                "upload-net-error": "网络错误，请重试"
            },
            tips: {
                "set-reprintable-success": "设置转载状态成功",
                "set-reprintable-fail": "设置转载状态失败"
            }
        }
